const countryData = {
  AE: { currencyCode: "AED", currencyName: "UAE Dirham", countryName: "United Arab Emirates" },
  AF: { currencyCode: "AFN", currencyName: "Afghan Afghani", countryName: "Afghanistan" },
  AG: { currencyCode: "XCD", currencyName: "East Caribbean Dollar", countryName: "Antigua and Barbuda" },
  AL: { currencyCode: "ALL", currencyName: "Albanian Lek", countryName: "Albania" },
  AM: { currencyCode: "AMD", currencyName: "Armenian Dram", countryName: "Armenia" },
  AN: { currencyCode: "ANG", currencyName: "Netherlands Antillian Guilder", countryName: "Netherlands Antilles" },
  AO: { currencyCode: "AOA", currencyName: "Angolan Kwanza", countryName: "Angola" },
  AQ: { currencyCode: "AQD", currencyName: "", countryName: "Antarctica" },
  AR: { currencyCode: "ARS", currencyName: "Argentine Peso", countryName: "Argentina" },
  AU: { currencyCode: "AUD", currencyName: "Australian Dollar", countryName: "Australia" },
  AZ: { currencyCode: "AZN", currencyName: "Azerbaijani Manat", countryName: "Azerbaijan" },
  BA: { currencyCode: "BAM", currencyName: "Bosnia and Herzegovina Mark", countryName: "Bosnia and Herzegovina" },
  BB: { currencyCode: "BBD", currencyName: "Barbados Dollar", countryName: "Barbados" },
  BD: { currencyCode: "BDT", currencyName: "Bangladeshi Taka", countryName: "Bangladesh" },
  BE: { currencyCode: "XOF", currencyName: "West African CFA franc", countryName: "Benin" },
  BG: { currencyCode: "BGN", currencyName: "Bulgarian Lev", countryName: "Bulgaria" },
  BH: { currencyCode: "BHD", currencyName: "Bahraini Dinar", countryName: "Bahrain" },
  BI: { currencyCode: "BIF", currencyName: "Burundian Franc", countryName: "Burundi" },
  BM: { currencyCode: "BMD", currencyName: "Bermudian Dollar", countryName: "Bermuda" },
  BN: { currencyCode: "BND", currencyName: "Brunei Dollar", countryName: "Brunei" },
  BO: { currencyCode: "BOB", currencyName: "Bolivian Boliviano", countryName: "Bolivia" },
  BR: { currencyCode: "BRL", currencyName: "Brazilian Real", countryName: "Brazil" },
  BS: { currencyCode: "BSD", currencyName: "Bahamian Dollar", countryName: "Bahamas" },
  BV: { currencyCode: "NOK", currencyName: "Norwegian Krone", countryName: "Bouvet Island" },
  BW: { currencyCode: "BWP", currencyName: "Botswana Pula", countryName: "Botswana" },
  BY: { currencyCode: "BYR", currencyName: "Belarusian Ruble", countryName: "Belarus" },
  BZ: { currencyCode: "BZD", currencyName: "Belize Dollar", countryName: "Belize" },
  CA: { currencyCode: "CAD", currencyName: "Canadian Dollar", countryName: "Canada" },
  CD: { currencyCode: "CDF", currencyName: "Congolese Franc", countryName: "Democratic Republic of the Congo" },
  CF: { currencyCode: "XAF", currencyName: "Central African CFA Franc", countryName: "Central African Republic" },
  CH: { currencyCode: "CHF", currencyName: "Swiss Franc", countryName: "Switzerland" },
  CL: { currencyCode: "CLP", currencyName: "Chilean Peso", countryName: "Chile" },
  CN: { currencyCode: "CNY", currencyName: "Chinese Renminbi", countryName: "China" },
  CO: { currencyCode: "COP", currencyName: "Colombian Peso", countryName: "Colombia" },
  CR: { currencyCode: "CRC", currencyName: "Costa Rican Colon", countryName: "Costa Rica" },
  CU: { currencyCode: "CUP", currencyName: "Cuban Peso", countryName: "Cuba" },
  CV: { currencyCode: "CVE", currencyName: "Cape Verdean Escudo", countryName: "Cape Verde" },
  CY: { currencyCode: "CYP", currencyName: "Cypriot Pound", countryName: "Cyprus" },
  CZ: { currencyCode: "CZK", currencyName: "Czech Koruna", countryName: "Czech Republic" },
  DJ: { currencyCode: "DJF", currencyName: "Djiboutian Franc", countryName: "Djibouti" },
  DK: { currencyCode: "DKK", currencyName: "Danish Krone", countryName: "Denmark" },
  DO: { currencyCode: "DOP", currencyName: "Dominican Peso", countryName: "Dominican Republic" },
  DZ: { currencyCode: "DZD", currencyName: "Algerian Dinar", countryName: "Algeria" },
  EC: { currencyCode: "ECS", currencyName: "Ecuadorian Sucre", countryName: "Ecuador" },
  EE: { currencyCode: "EEK", currencyName: "Estonian Kroon", countryName: "Estonia" },
  EG: { currencyCode: "EGP", currencyName: "Egyptian Pound", countryName: "Egypt" },
  ET: { currencyCode: "ETB", currencyName: "Ethiopian Birr", countryName: "Ethiopia" },
  FJ: { currencyCode: "FJD", currencyName: "Fiji Dollar", countryName: "Fiji" },
  FK: { currencyCode: "FKP", currencyName: "Falkland Islands Pound", countryName: "Falkland Islands" },
  FR: { currencyCode: "EUR", currencyName: "Euro", countryName: "France or European Union" },
  GB: { currencyCode: "GBP", currencyName: "Pound Sterling", countryName: "United Kingdom" },
  GE: { currencyCode: "GEL", currencyName: "Georgian Lari", countryName: "Georgia" },
  GG: { currencyCode: "GGP", currencyName: "Guernsey Pound", countryName: "Guernsey" },
  GH: { currencyCode: "GHS", currencyName: "Ghanaian Cedi", countryName: "Ghana" },
  GI: { currencyCode: "GIP", currencyName: "Gibraltar Pound", countryName: "Gibraltar" },
  GM: { currencyCode: "GMD", currencyName: "Gambian Dalasi", countryName: "Gambia" },
  GN: { currencyCode: "GNF", currencyName: "Guinean Franc", countryName: "Guinea" },
  GT: { currencyCode: "GTQ", currencyName: "Guatemalan Quetzal", countryName: "Guatemala" },
  GY: { currencyCode: "GYD", currencyName: "Guyanese Dollar", countryName: "Guyana" },
  HK: { currencyCode: "HKD", currencyName: "Hong Kong Dollar", countryName: "Hong Kong" },
  HN: { currencyCode: "HNL", currencyName: "Honduran Lempira", countryName: "Honduras" },
  HR: { currencyCode: "HRK", currencyName: "Croatian Kuna", countryName: "Croatia" },
  HT: { currencyCode: "HTG", currencyName: "Haitian Gourde", countryName: "Haiti" },
  HU: { currencyCode: "HUF", currencyName: "Hungarian Forint", countryName: "Hungary" },
  ID: { currencyCode: "IDR", currencyName: "Indonesian Rupiah", countryName: "Indonesia" },
  IL: { currencyCode: "ILS", currencyName: "Israeli New Shekel", countryName: "Israel" },
  IN: { currencyCode: "INR", currencyName: "Indian Rupee", countryName: "India" },
  IQ: { currencyCode: "IQD", currencyName: "Iraqi Dinar", countryName: "Iraq" },
  IR: { currencyCode: "IRR", currencyName: "Iranian Rial", countryName: "Iran" },
  IS: { currencyCode: "ISK", currencyName: "Icelandic Króna", countryName: "Iceland" },
  JM: { currencyCode: "JMD", currencyName: "Jamaican Dollar", countryName: "Jamaica" },
  JO: { currencyCode: "JOD", currencyName: "Jordanian Dinar", countryName: "Jordan" },
  JP: { currencyCode: "JPY", currencyName: "Japanese Yen", countryName: "Japan" },
  KE: { currencyCode: "KES", currencyName: "Kenyan Shilling", countryName: "Kenya" },
  KG: { currencyCode: "KGS", currencyName: "Kyrgyzstani Som", countryName: "Kyrgyzstan" },
  KH: { currencyCode: "KHR", currencyName: "Cambodian Riel", countryName: "Cambodia" },
  KM: { currencyCode: "KMF", currencyName: "Comorian Franc", countryName: "Comoros" },
  KP: { currencyCode: "KPW", currencyName: "North Korean Won", countryName: "North Korea" },
  KR: { currencyCode: "KRW", currencyName: "South Korean Won", countryName: "South Korea" },
  KW: { currencyCode: "KWD", currencyName: "Kuwaiti Dinar", countryName: "Kuwait" },
  KY: { currencyCode: "KYD", currencyName: "Cayman Islands Dollar", countryName: "Cayman Islands" },
  KZ: { currencyCode: "KZT", currencyName: "Kazakhstani Tenge", countryName: "Kazakhstan" },
  LA: { currencyCode: "LAK", currencyName: "Lao Kip", countryName: "Laos" },
  LB: { currencyCode: "LBP", currencyName: "Lebanese Pound", countryName: "Lebanon" },
  LK: { currencyCode: "LKR", currencyName: "Sri Lanka Rupee", countryName: "Sri Lanka" },
  LR: { currencyCode: "LRD", currencyName: "Liberian Dollar", countryName: "Liberia" },
  LS: { currencyCode: "LSL", currencyName: "Lesotho Loti", countryName: "Lesotho" },
  LT: { currencyCode: "LTL", currencyName: "Lithuanian Litas", countryName: "Lithuania" },
  LV: { currencyCode: "LVL", currencyName: "Latvian Lats", countryName: "Latvia" },
  LY: { currencyCode: "LYD", currencyName: "Libyan Dinar", countryName: "Libya" },
  MA: { currencyCode: "MAD", currencyName: "Moroccan Dirham", countryName: "Morocco" },
  MD: { currencyCode: "MDL", currencyName: "Moldovan Leu", countryName: "Moldova" },
  MG: { currencyCode: "MGA", currencyName: "Malagasy Ariary", countryName: "Madagascar" },
  MK: { currencyCode: "MKD", currencyName: "Macedonian Denar", countryName: "North Macedonia" },
  MM: { currencyCode: "MMK", currencyName: "Burmese Kyat", countryName: "Myanmar" },
  MN: { currencyCode: "MNT", currencyName: "Mongolian Tögrög", countryName: "Mongolia" },
  MO: { currencyCode: "MOP", currencyName: "Macanese Pataca", countryName: "Macau" },
  MR: { currencyCode: "MRO", currencyName: "Mauritanian Ouguiya", countryName: "Mauritania" },
  MT: { currencyCode: "MTL", currencyName: "Maltese Lira", countryName: "Malta" },
  MU: { currencyCode: "MUR", currencyName: "Mauritian Rupee", countryName: "Mauritius" },
  MV: { currencyCode: "MVR", currencyName: "Maldivian Rufiyaa", countryName: "Maldives" },
  MW: { currencyCode: "MWK", currencyName: "Malawian Kwacha", countryName: "Malawi" },
  MX: { currencyCode: "MXN", currencyName: "Mexican Peso", countryName: "Mexico" },
  MY: { currencyCode: "MYR", currencyName: "Malaysian Ringgit", countryName: "Malaysia" },
  MZ: { currencyCode: "MZN", currencyName: "Mozambican Metical", countryName: "Mozambique" },
  NA: { currencyCode: "NAD", currencyName: "Namibian Dollar", countryName: "Namibia" },
  NC: { currencyCode: "XPF", currencyName: "CFP Franc", countryName: "New Caledonia" },
  NG: { currencyCode: "NGN", currencyName: "Nigerian Naira", countryName: "Nigeria" },
  NI: { currencyCode: "NIO", currencyName: "Nicaraguan Córdoba", countryName: "Nicaragua" },
  NP: { currencyCode: "NPR", currencyName: "Nepalese Rupee", countryName: "Nepal" },
  NZ: { currencyCode: "NZD", currencyName: "New Zealand Dollar", countryName: "New Zealand" },
  OM: { currencyCode: "OMR", currencyName: "Omani Rial", countryName: "Oman" },
  PA: { currencyCode: "PAB", currencyName: "Panamanian Balboa", countryName: "Panama" },
  PE: { currencyCode: "PEN", currencyName: "Peruvian Sol", countryName: "Peru" },
  PG: { currencyCode: "PGK", currencyName: "Papua New Guinean Kina", countryName: "Papua New Guinea" },
  PH: { currencyCode: "PHP", currencyName: "Philippine Peso", countryName: "Philippines" },
  PK: { currencyCode: "PKR", currencyName: "Pakistani Rupee", countryName: "Pakistan" },
  PL: { currencyCode: "PLN", currencyName: "Polish Złoty", countryName: "Poland" },
  PY: { currencyCode: "PYG", currencyName: "Paraguayan Guaraní", countryName: "Paraguay" },
  QA: { currencyCode: "QAR", currencyName: "Qatari Riyal", countryName: "Qatar" },
  RO: { currencyCode: "RON", currencyName: "Romanian Leu", countryName: "Romania" },
  RS: { currencyCode: "RSD", currencyName: "Serbian Dinar", countryName: "Serbia" },
  RU: { currencyCode: "RUB", currencyName: "Russian Ruble", countryName: "Russia" },
  RW: { currencyCode: "RWF", currencyName: "Rwandan Franc", countryName: "Rwanda" },
  SA: { currencyCode: "SAR", currencyName: "Saudi Riyal", countryName: "Saudi Arabia" },
  SB: { currencyCode: "SBD", currencyName: "Solomon Islands Dollar", countryName: "Solomon Islands" },
  SC: { currencyCode: "SCR", currencyName: "Seychellois Rupee", countryName: "Seychelles" },
  SD: { currencyCode: "SDG", currencyName: "Sudanese Pound", countryName: "Sudan" },
  SE: { currencyCode: "SEK", currencyName: "Swedish Krona", countryName: "Sweden" },
  SG: { currencyCode: "SGD", currencyName: "Singapore Dollar", countryName: "Singapore" },
  SK: { currencyCode: "SKK", currencyName: "Slovak Koruna", countryName: "Slovakia" },
  SL: { currencyCode: "SLL", currencyName: "Sierra Leonean Leone", countryName: "Sierra Leone" },
  SO: { currencyCode: "SOS", currencyName: "Somali Shilling", countryName: "Somalia" },
  SR: { currencyCode: "SRD", currencyName: "Surinamese Dollar", countryName: "Suriname" },
  ST: { currencyCode: "STN", currencyName: "São Tomé and Príncipe Dobra", countryName: "São Tomé and Príncipe" },
  SV: { currencyCode: "SVC", currencyName: "Salvadoran colón", countryName: "El Salvador" },
  SY: { currencyCode: "SYP", currencyName: "Syrian Pound", countryName: "Syria" },
  SZ: { currencyCode: "SZL", currencyName: "Eswatini Lilangeni", countryName: "Eswatini" },
  TH: { currencyCode: "THB", currencyName: "Thai Baht", countryName: "Thailand" },
  TJ: { currencyCode: "TJS", currencyName: "Tajikistani Somoni", countryName: "Tajikistan" },
  TM: { currencyCode: "TMT", currencyName: "Turkmenistan Manat", countryName: "Turkmenistan" },
  TN: { currencyCode: "TND", currencyName: "Tunisian Dinar", countryName: "Tunisia" },
  TO: { currencyCode: "TOP", currencyName: "Tongan Paʻanga", countryName: "Tonga" },
  TR: { currencyCode: "TRY", currencyName: "Turkish Lira", countryName: "Turkey" },
  TT: { currencyCode: "TTD", currencyName: "Trinidad and Tobago Dollar", countryName: "Trinidad and Tobago" },
  TW: { currencyCode: "TWD", currencyName: "New Taiwan Dollar", countryName: "Taiwan" },
  TZ: { currencyCode: "TZS", currencyName: "Tanzanian Shilling", countryName: "Tanzania" },
  UA: { currencyCode: "UAH", currencyName: "Ukrainian Hryvnia", countryName: "Ukraine" },
  UG: { currencyCode: "UGX", currencyName: "Ugandan Shilling", countryName: "Uganda" },
  US: { currencyCode: "USD", currencyName: "United States Dollar", countryName: "United States" },
  UY: { currencyCode: "UYU", currencyName: "Uruguayan Peso", countryName: "Uruguay" },
  UZ: { currencyCode: "UZS", currencyName: "Uzbekistani So'm", countryName: "Uzbekistan" },
  VE: { currencyCode: "VES", currencyName: "Venezuelan Bolívar Soberano", countryName: "Venezuela" },
  VN: { currencyCode: "VND", currencyName: "Vietnamese Đồng", countryName: "Vietnam" },
  VU: { currencyCode: "VUV", currencyName: "Vanuatu Vatu", countryName: "Vanuatu" },
  YE: { currencyCode: "YER", currencyName: "Yemeni Rial", countryName: "Yemen" },
  ZA: { currencyCode: "ZAR", currencyName: "South African Rand", countryName: "South Africa" },
  ZM: { currencyCode: "ZMK", currencyName: "Zambian Kwacha", countryName: "Zambia" },
  ZW: { currencyCode: "ZWL", currencyName: "Zimbabwean Dollar", countryName: "Zimbabwe" }
};

